### ISSUE TITLE
Various apps show placeholder icons

### ISSUE THREAD

**Issue by codygarver** [elementary/appstream-data#1]
Was a bug in Loki

**Comment by codygarver** [comment]
The apps are:
* Code
* Music
* Plank
* Screenshot
* Steam

**Comment by rythmkraze** [comment]
The app "Clairvoyant" as well shows a placeholder icon

**Comment by cassidyjames** [comment]
@rythmkraze are you seeing a gray circle for Clairvoyant, i.e. https://github.com/cassidyjames/clairvoyant/issues/3?

**Comment by rythmkraze** [comment]
It was the generic placeholder icon "application-default-icon". Not the gray circle shown in  cassidyjames/clairvoyant#3 

But after a restart, I now see the correct icon.

**Comment by danirabbit** [comment]
Gonna drop from the milestone since this was already in issue in Loki

**Comment by kgrubb** [comment]
This is likely resolved via https://github.com/elementary/appstream-data/pull/15.

**Comment by 4jNsY6fCVqZv** [comment]
Whoa, looks very good now! Thanks!
Only Gstreamer & Wallpapers show the generic standard icon.
Are there any icons that would do better?

**Comment by cassidyjames** [comment]
We don't maintain GStreamer, so we don't control the icon they use. Wallpapers has been filed as an issue here https://github.com/elementary/wallpapers/issues/88

**Comment by 4jNsY6fCVqZv** [comment]
Thanks for your feedback and that already opened Issue for Wallpaper!
Are you also saying that you had no influence on Firefox now displaying an icon in AppCenter? I thought you did something about it and therefore can solve it for GStreamer the same way. But okay, then I do understand.
A fallback doesn't make sense, does it?

**Comment by danirabbit** [comment]
This is already closed, but just following up: we now show icons for lots of different components and provide better fallbacks for certain component types (like themes, fonts libraries, etc). Any outstanding components should get their own individual issues
