### ISSUE TITLE
Icons not displaying for apps such as Code or Music in Appcenter

### ISSUE THREAD

**Issue by NathanBnm** [elementary/appstream-data#13]
Icons for Screenshot, Music and Code apps from elementary LLC. aren't displaying in the AppCenter.
Here is a screenshot:

![image](https://user-images.githubusercontent.com/45366162/51692495-52550000-1ffd-11e9-9eb8-59da21ca96eb.png)

**Comment by 4jNsY6fCVqZv** [comment]
This issue can be closed, right?

**Comment by NathanBnm** [comment]
Fixed on my side.
