### ISSUE TITLE
Update to noble

### ISSUE THREAD

**Issue by ryonakano** [elementary/appstream-data#32]
### Problem

We're building appstream-metadata for Horus (jammy) in the current master branch. I guess we need to update to noble before releasing OS 8

### Proposal

- [x] Prevent automatic update for jammy
  - [x] Create `jammy` branch in this repository
  - [x] Switch `master` to `jammy` in the Recipe contents section in [the appstream-data-jammy recipe](https://code.launchpad.net/~elementary-os/+recipe/appstream-data-jammy)
- [x] Update this repository to build for noble

### Prior Art (Optional)

#29  and #21

**Comment by danirabbit** [comment]
Marking this as blocked because we actually need a stable docker container first before we can build appdata

**Comment by Miqueas** [comment]
Does this means that OS 8 will still be based on Ubuntu Jammy? 🤔

**Comment by ryonakano** [comment]
@Miqueas No, it will be based on noble.

The current master branch is for OS 7, so making changes for OS 8 to the master would break things in OS 7. So, we need some work for OS 7 before OS 8.

**Comment by Miqueas** [comment]
Oohh I get it, thanks for your answer

**Comment by danirabbit** [comment]
@ryonakano I have a branch here for stable docker container :) https://github.com/elementary/docker/pull/44

**Comment by danirabbit** [comment]
- [x] Switched focus branch to Noble and new metadata was built: https://github.com/elementary/appstream-data
- [x] Set up new recipe, import is in an hour: https://code.launchpad.net/~elementary-os/+recipe/appstream-data-noble

For now, I didn't touch the workflow on the jammy branch. I think we're still occasionally pushing certain updates there, so I figure as long as we're making new releases might as well keep building it :woman_shrugging:

**Comment by danirabbit** [comment]
Built! Should be published soon. So closing as fixed :)

https://code.launchpad.net/~elementary-os/+archive/ubuntu/stable/+packages?field.name_filter=appstream&field.status_filter=published&field.series_filter=noble

**Comment by Miqueas** [comment]
Nice
